<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>

    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="3.10.4" />
    <PackageReference Include="MSTest.TestFramework" Version="3.10.4" />
    <PackageReference Include="Testcontainers" Version="4.11.0" />
    <PackageReference Include="Testcontainers.LocalStack" Version="4.11.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" Version="8.10.0" />
    <PackageReference Include="Moq" Version="4.20.72" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FiapX.Application\FiapX.Application.csproj" />
    <ProjectReference Include="..\..\src\FiapX.Domain\FiapX.Domain.csproj" />
    <ProjectReference Include="..\..\src\FiapX.Infra.Observability\FiapX.Infra.Observability.csproj" />
  </ItemGroup>

</Project>
