app:
  project: fiapx
  name: notifier
  version: 1.0.0
  env: dev

image:
  repository: ""
  tag: latest

email:
  smtpServer: mailpit-smtp
  smtpPort: 25
  sslRequired: false
  senderName: FIAP X
  senderAddress: "postmaster@fiapx.io"
  logoUrl: "https://d2nyagk7gn75jo.cloudfront.net/logo_video.svg"
  downloadBaseUrl: "https://d2nyagk7gn75jo.cloudfront.net/videos"

aws:
  useLocalstack: false
  region: us-east-1

queue:
  event: VideoProcessingCompleted
  name: "video-processing-completed"
  url: ""

datadog:
  otlpEndpoint: "https://otlp.us5.datadoghq.com"

secrets:
  clusterSecretStore: fiapx-aws-secrets
