apiVersion: keda.sh/v1alpha1
kind: ScaledJob

metadata:
  name: {{ .Values.app.name }}

spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: {{ .Values.app.name }}
            image: {{ .Values.image.repository | required "Parameter image.repository is required." }}:{{ .Values.image.tag }}
            imagePullPolicy: Always

            envFrom:
              - configMapRef:
                  name: {{ .Values.app.name }}-configs

            env:
              - name: EmailSenderOptions__UserName
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-email
                    key: userName
              - name: EmailSenderOptions__Password
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-email
                    key: password
              - name: AwsCredentials__AccessKey
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-aws
                    key: access-key-id
              - name: AwsCredentials__SecretAccessKey
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-aws
                    key: secret-access-key
              - name: AwsCredentials__SessionToken
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-aws
                    key: session-token
              - name: Datadog__ApiKey
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.app.name }}-datadog
                    key: api-key
                    optional: true

        restartPolicy: Never

  triggers:
    - type: aws-sqs-queue
      metadata:
        queueURL: {{ .Values.queue.url | required "Parameter queue.url is required." | quote }}
        queueLength: "1"
        awsRegion: {{ .Values.aws.region | quote }}
      authenticationRef:
        name: {{ .Values.app.name }}-keda-auth
